#! /bin/sh -e

prefix=`cd _prefix && pwd`

mkdir -p _build/cpanm
cd _build/cpanm

curl -kO https://github.com/miyagawa/cpanminus/raw/master/cpanm
chmod 755 cpanm

mkdir -p "$prefix/bin"
mv -f cpanm "$prefix/bin"

export PERL_CPANM_HOME=`pwd`
export PATH="$PATH:$prefix/bin"

cpanm -L "$prefix" Net::Amazon::EC2
cpanm -L "$prefix" Net::Amazon::S3
