#! /bin/sh -e

prefix=`cd _prefix && pwd`
name=fltk-1.3.x-r8550

cd _build
bunzip2 -c "../archive/$name.tar.bz2" | tar xf -
cd "$name"
./configure \
  --prefix "$prefix" \
  --enable-localjpeg \
  --enable-localzlib \
  --enable-localpng
make
make install
